name: 'CapRover Deploy Token'
description: 'Action to deploy on Caprover server'
author: 'Alexey Schebelev'
branding:
  icon: upload-cloud
  color: orange
inputs:
  server:
    description: 'CapRover admin panel URL. Ex. https://captain.root.domain.com'
    required: true
  token:
    description: 'CapRover application token. Use $\{{ secrets.CAPROVER_TOKEN }} for better security.'
    required: true
  appname:
    description: 'Application name on the CapRover server. Must exists.'
    required: true
  branch:
    description: 'Branch which will be deployed'
    required: false
    default: 'master'
runs:
  using: 'docker'
  image: 'Dockerfile'
